name: downup
description: "Sedang dalam proses....."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  http: ^1.2.2
  dio: ^5.2.0
  path_provider: ^2.0.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.5
  flutter_spinkit: ^5.2.0
  lottie: ^3.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true